// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgyfCJPm5GRg8t1pZ-_FjmLTTCp7ap3Ps',
    appId: '1:775951311142:web:38094dd353ded1ebd461e7',
    messagingSenderId: '775951311142',
    projectId: 'muster-clone',
    authDomain: 'muster-clone.firebaseapp.com',
    storageBucket: 'muster-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfgimToNBSJSE_1-bqT_Fz5bIBhwFpxM',
    appId: '1:775951311142:android:adf1801dd0c80abdd461e7',
    messagingSenderId: '775951311142',
    projectId: 'muster-clone',
    storageBucket: 'muster-clone.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpKFRqsF_5YfBXDOt49ebYg9W5LCgNwI',
    appId: '1:775951311142:ios:cb57cdfa4d54b699d461e7',
    messagingSenderId: '775951311142',
    projectId: 'muster-clone',
    storageBucket: 'muster-clone.firebasestorage.app',
    iosClientId:
        '775951311142-kpoi4ijd0te3a4es6m3na82t8lprhss4.apps.googleusercontent.com',
    iosBundleId: 'com.muster.sport',
  );
}
